### ISSUE TITLE
wps_convolution config builder

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/osprey#15]
RVIC 1.1.0.post1 runs based only on config files, which degrades the user-friendliness of the software. Therefore, a `config_builder` program, which takes user inputs to create config files, is needed for each process. 

For `RVIC convolution`, refer to the [document](https://rvic.readthedocs.io/en/latest/user-guide/convolution/) page to see what contents should be included in the config file. @corviday do you have some advice on setting the direction to implement this program such as setting default values?

**Comment by corviday** [comment]
[Here's](https://github.com/pacificclimate/data-prep-actions/blob/master/actions/make-rvic-grid/rvic-queuer.py) a script that - amoung other things - writes config files. It includes a lot of default values (anything in the config-writing sections that isn't a variable), but there are some things that I wrote defaults for that you might want to make flexible. For example, I included defaults for the variable names inside the files, because I expected we'd always use the standard PCIC names, but non-PCIC people might use the WPS service and have different names for their file variables.

**Comment by corviday** [comment]
That script is slightly complicated, it actually outputs _another_ script. Then the output script is run on our data processing computers, and it creates the config files and runs the RVIC processes with them. But I hope it would be pretty straightforward to see what the config defaults are from the code, even though that script does not directly output them.
