### ISSUE TITLE
Wrap RVIC convert module into wps

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/osprey#9]
The [`convert`](https://github.com/UW-Hydro/RVIC/blob/master/rvic/convert.py) module is responsible for "providing users with the ability to convert old routing model setups into RVIC parameters." Wrap this into a `process` that can handle either a `file` or `dict` object as input. Follow the [`script`](https://github.com/UW-Hydro/RVIC/blob/master/scripts/rvic) for other inputs that may be needed.
 
Things we need to add:
- The `process`
- A `pytest` suite
- A `notebook` demo (can be an individual demo for now)

Ensure that you:
- Test both locally and on the `docker` server
- Make note of any changes required in `RVIC` in this thread

**Comment by sum1lim** [comment]
[RVIC convert docs](https://rvic.readthedocs.io/en/latest/user-guide/conversion/)

**Comment by sum1lim** [comment]
Finding the right resource and information about `RVIC convert` module is somewhat challenging. In order to write the WPS program, sample input [UHS files](https://github.com/UW-Hydro/RVIC/blob/master/rvic/convert.py#L3) are needed. @corviday do you have an idea of what UHS files are?

**Comment by corviday** [comment]
Sorry, no. I’ve never used that function of RVIC. I don’t know if anyone at
PCIC has.

On Jul 28, 2020, at 1:22 PM, Sangwon Lim <notifications@github.com> wrote:

﻿

Finding the right resource and information about RVIC convert module is
somewhat challenging. In order to write the WPS program, sample input UHS
files <https://github.com/UW-Hydro/RVIC/blob/master/rvic/convert.py#L3> are
needed. @corviday <https://github.com/corviday> do you have an idea of what
UHS files are?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pacificclimate/osprey/issues/9#issuecomment-665263181>,
or unsubscribe
